# Setup
title:               Darmowiyarjo Notes
tagline:             'DN'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 https://darmowiyarjo.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Darmowiyarjo
  url:               https://google.com
  email:             darmowiyarjonotes@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
